In [13]:
import pandas as pd

df_cl = pd.read_csv("../data/tig_train.csv")

df_cl.head()

,user_reported,action_taken,label,word_count,char_count,avg_word_length,has_number,uppercase_ratio,punctuation_count,has_harmful_keyword,...,keyword_and_reported,type_comment,type_status,type_replay,type_post,type_share,length_very_short,length_short,length_medium,length_long
0,0,1,0,14,73,5.214286,0,0.000000,9,0,...,0,True,False,False,False,False,False,True,False,False
1,0,0,0,3,16,5.333333,0,0.000000,0,0,...,0,False,True,False,False,False,True,False,False,False
2,0,0,0,4,14,3.500000,0,0.000000,0,0,...,0,False,False,True,False,False,True,False,False,False
3,1,1,1,75,339,4.520000,1,0.023599,8,0,...,0,False,False,False,True,False,False,False,False,True
4,0,0,0,10,49,4.900000,0,0.000000,3,1,...,0,False,True,False,False,False,False,True,False,False

In [14]:
df_cl.columns

Index(['user_reported', 'action_taken', 'label', 'word_count', 'char_count',
       'avg_word_length', 'has_number', 'uppercase_ratio', 'punctuation_count',
       'has_harmful_keyword', 'harmful_keyword_count', 'post_hour',
       'post_dayofweek', 'is_weekend', 'post_month', 'post_year',
       'days_since_post', 'user_is_reported', 'action_flagged', 'city_freq',
       'is_major_city', 'report_action_mismatch', 'harmful_no_action',
       'no_keyword_but_action', 'keyword_and_reported', 'type_comment',
       'type_status', 'type_replay', 'type_post', 'type_share',
       'length_very_short', 'length_short', 'length_medium', 'length_long'],
      dtype='object')

In [15]:
df_cl.shape

(48, 34)

In [24]:
df_te = pd.read_csv("../data/tig_test.csv")

df_te.head()

,user_reported,action_taken,label,word_count,char_count,avg_word_length,has_number,uppercase_ratio,punctuation_count,has_harmful_keyword,...,keyword_and_reported,type_comment,type_status,type_replay,type_post,type_share,length_very_short,length_short,length_medium,length_long
0,1,1,1,16,85,5.312500,0,0.0,7,0,...,0,False,0,0,True,False,False,False,True,False
1,1,1,1,3,10,3.333333,0,0.0,0,1,...,1,False,0,0,False,True,True,False,False,False
2,0,0,0,4,24,6.000000,0,0.0,0,0,...,0,True,0,0,False,False,True,False,False,False
3,1,0,0,5,19,3.800000,0,0.0,0,0,...,0,True,0,0,False,False,True,False,False,False
4,0,1,0,2,7,3.500000,0,0.0,0,0,...,0,True,0,0,False,False,True,False,False,False

In [25]:
df_te.shape

(17, 34)

In [21]:
df = pd.read_csv("../data/tig_meta_data.csv")

df.head()

,id,name,date,content,label,language,post_type,user_reported,action_taken,city
0,1.0,Biniam Girmay,2019-08-13,ነዚኦም አማ ብሓደ ጌርካ ምጉሓፎም አዩ ኔሩ,Harmful,Tigrinya,post,True,Removed,Mekelle
1,2.0,Almaz gual gere,2018-11-09,ደሓን ኩን ሓደ እተወላዊ ሰብ ናትካ ኣብ ሓበሬታ ኣለኹ,Neutral,Tigrinya,comment,False,none,Addis Ababa
2,3.0,Hagos Berhe,2018-04-29,ክሊቲኦም ህዝቢታት ብጣዕሚ ቅርሕንቲ አለዎም ዝፍታሕ ውን አይመስለንን?,Harmful,Tigrinya,share,False,Warning,Asmera
3,4.0,Selam,2020-01-05,ሓበሬታ ለውጢ ሰላም ንምግባር ኣሎ,Neutral,Tigrinya,post,True,none,Adama
4,5.0,Fikerte,2020-12-05,ቡዳ፤ጠቢብ፤በላዕቲ ሰብ አዮም ኮ አሳቶም አይትፈልጥን ዲካ?,Harmful,Tigrinya,comment,False,Removed,Bahr dar

In [22]:
df.columns

Index(['id', 'name', 'date', 'content', 'label', 'language', 'post_type',
       'user_reported', 'action_taken', 'city'],
      dtype='object')

In [23]:
df.shape

(65, 10)